# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Build and test for ${{ matrix.os }} - ${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        env:
            CI: true
            PLAYWRIGHT_BROWSERS_PATH: 0

        strategy:
            fail-fast: false
            matrix:
                node-version: [12.x, 15.x]
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Use cached node_modules
              id: cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: npm-v3-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-v3-${{ matrix.os }}-${{ matrix.node-version }}-

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install --legacy-peer-deps --no-audit

            - name: Run Tests
              run: npm test
